---
- client_id: 0B:28:2C:C5:99:80:AD:83:5D:8E:6B:63:1D:D4:9E:37:46:F6:C9:01:keyid:0B:28:2C:C5:99:80:AD:83:5D:8E:6B:63:1D:D4:9E:37:46:F6:C9:01
  client_name: provider-clarus
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://provider-clarus.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: af94412ae6317a66b379ce77753f1574cf9e0b4b74502eaaf138ce8bdc70bb66
- client_id: E8:B2:26:4E:52:83:19:AE:B0:EB:5F:95:34:74:A6:79:77:88:DB:22:keyid:E8:B2:26:4E:52:83:19:AE:B0:EB:5F:95:34:74:A6:79:77:88:DB:22
  client_name: consumer-clarus
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://consumer-clarus.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: 239467254fabd1f78a06fb866d1b954e69075b1f64da5a8b5cadc829b004d5bb