---
- client_id: 0B:28:2C:C5:99:80:AD:83:5D:8E:6B:63:1D:D4:9E:37:46:F6:C9:01:keyid:0B:28:2C:C5:99:80:AD:83:5D:8E:6B:63:1D:D4:9E:37:46:F6:C9:01
  client_name: provider-clarus
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://provider-clarus.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: af94412ae6317a66b379ce77753f1574cf9e0b4b74502eaaf138ce8bdc70bb66
- client_id: E8:B2:26:4E:52:83:19:AE:B0:EB:5F:95:34:74:A6:79:77:88:DB:22:keyid:E8:B2:26:4E:52:83:19:AE:B0:EB:5F:95:34:74:A6:79:77:88:DB:22
  client_name: consumer-clarus
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://consumer-clarus.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: 239467254fabd1f78a06fb866d1b954e69075b1f64da5a8b5cadc829b004d5bb
- client_id: C3:C3:59:0D:CD:0A:93:6C:5B:06:1B:44:60:26:0E:79:03:75:C5:22:keyid:C3:C3:59:0D:CD:0A:93:6C:5B:06:1B:44:60:26:0E:79:03:75:C5:22
  client_name: luigi-tc-consumer-clarus
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://luigi-tc-consumer-clarus.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: de34f6b68abaf9b0a71ff3a9615e303e7cb00f1bf246a9bcd454a1847086a770
- client_id: 12:42:6F:FA:DA:98:4D:32:CE:DB:EA:EA:BC:6C:9A:BF:D8:83:4A:FE:keyid:12:42:6F:FA:DA:98:4D:32:CE:DB:EA:EA:BC:6C:9A:BF:D8:83:4A:FE
  client_name: luigi-tc-provider-clarus
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://luigi-tc-provider-clarus.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: f76e87cd433437df01e1230b9d9b20334b0065260ca199afa2f80203968c6bc5
- client_id: 4F:B3:D5:22:6F:F6:80:1C:9E:4B:27:4F:5D:4C:52:D7:30:70:6A:98:keyid:4F:B3:D5:22:6F:F6:80:1C:9E:4B:27:4F:5D:4C:52:D7:30:70:6A:98
  client_name: ikerlan-tc-edge
  grant_types: client_credentials
  token_endpoint_auth_method: private_key_jwt
  scope: idsc:IDS_CONNECTOR_ATTRIBUTES_ALL
  attributes:
  - key: idsc
    value: IDS_CONNECTOR_ATTRIBUTES_ALL
  - key: securityProfile
    value: idsc:BASE_SECURITY_PROFILE
  - key: referringConnector
    value: http://ikerlan-tc-edge.demo
  - key: "@type"
    value: ids:DatPayload
  - key: "@context"
    value: https://w3id.org/idsa/contexts/context.jsonld
  - key: transportCertsSha256
    value: 70819a64b423cdf2783cf5f87e592bc4cab9cca214954dbd85adec54a57222a6

